DROP TABLE IF EXISTS cars;

CREATE TABLE cars (
                      id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      make             VARCHAR(64)  NOT NULL,
                      model            VARCHAR(128) NOT NULL,
                      manufacture_year INTEGER      NOT NULL,
                      vin              VARCHAR(17)  NOT NULL,
                      odometer_km      INTEGER,
                      row_version      INTEGER,
                      created_at       TIMESTAMP    NOT NULL,
                      updated_at       TIMESTAMP    NOT NULL,
                      CONSTRAINT uk_cars_vin UNIQUE (vin)
);